service: nanowritlabs-app-ext-sceneBuider-recommitmentsTable

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-ext-recommitments

provider:
  name: aws
  stage: dev
  region: us-west-2

resources:
  Resources:
    RecommitmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: recommitmentId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: recommitmentId
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST

  Outputs:
    RecommitmentsTableArn:
      Value:
        Fn::GetAtt:
          - RecommitmentsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ExtRecommitmentsTableArn