service: nanowritlabs-app-ext-FirstLine-firstLinesTable

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-ext-firstLines

provider:
  name: aws
  stage: dev
  region: us-west-2

resources:
  Resources:
    FirstLinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: firstLineId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: firstLineId
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST

  Outputs:
    FirstLinesTableArn:
      Value:
        Fn::GetAtt:
          - FirstLinesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ExtFirstLinesTableArn